export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTHSIGNUP_REQUEST = "AUTHSIGNUP_REQUEST";
export const AUTHSIGNUP_SUCCESS = "AUTHSIGNUP_SUCCESS";
export const AUTHSIGNUP_FAILURE = "AUTHSIGNUP_FAILURE";
export const LOGOUT = "LOGOUT";